### ISSUE TITLE
Create a single float for 0.03928 instead of three

### ISSUE THREAD

**Issue by brielov** [tmcw/relative-luminance#20]
May be you can cache the 0.03928 float instead of creating three exact same values.

```javascript
  const magicNum = 0.03928;

  const r = rsrgb <= magicNum ? rsrgb * lowc : adjustGamma(rsrgb);
  const g = gsrgb <= magicNum ? gsrgb * lowc : adjustGamma(gsrgb);
  const b = bsrgb <= magicNum ? bsrgb * lowc : adjustGamma(bsrgb);
```

**Comment by tmcw** [comment]
Thanks for the suggestion! This is something that V8 does for us, roughly: comparing a cached version to an 'uncached' version of the algorithm produces identical performance results on my machine and Node v10: around 520 ops/millisecond.

Which also is enough that it's very unlikely that relative-luminance is a bottleneck in any program. Likely this is because the 'cached' version is going through [constant folding](https://en.wikipedia.org/wiki/Constant_folding) to avoid repeated accesses, but given the results I won't dig into the bytecode

If you find different benchmarking results, please do let me know.
